version: "3.9"
services:
  url_shortcut_db:
    container_name: url_shortcut_db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortcut
      PGDATA: /var/lib/postgresql/data/pgdata
      DB_HOST: 0.0.0.0
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432